import { Client } from '../types/client'

// Note: isPrime is used to determine which clients are displayed in the PrimeClient component, also the count of isPrime must be multiple of 6 {6, 12, 18,...}
export const CLIENTS: Client[] = [
    {
        id: 1,
        name: "Lumina Developments",
        logoImage: "https://images.pexels.com/photos/1337380/pexels-photo-1337380.jpeg",
        alt: "Lumina Developments Logo",
        description: "Innovative residential and commercial real estate developers.",
        isPrime: false,
    },
    {
        id: 2,
        name: "EcoBuild Systems",
        logoImage: "https://images.pexels.com/photos/430205/pexels-photo-430205.jpeg",
        alt: "EcoBuild Systems Logo",
        description: "Sustainable and eco-friendly construction solutions.",
        isPrime: true,
    },
    {
        id: 3,
        name: "Skyline Ventures",
        logoImage: "https://images.pexels.com/photos/1162361/pexels-photo-1162361.jpeg",
        alt: "Skyline Ventures Logo",
        description: "Global infrastructure and high-rise specialists.",
        isPrime: false,
    },
    {
        id: 4,
        name: "Veridian Group",
        logoImage: "https://images.pexels.com/photos/170809/pexels-photo-170809.jpeg",
        alt: "Veridian Group Logo",
        description: "Luxury hospitality and resort management.",
        isPrime: true,
    },
    {
        id: 5,
        name: "Apex Industrials",
        logoImage: "https://images.pexels.com/photos/1769735/pexels-photo-1769735.jpeg",
        alt: "Apex Industrials Logo",
        description: "Industrial complex design and heavy machinery logistics.",
        isPrime: false,
    },
    {
        id: 6,
        name: "Urban Pulse",
        logoImage: "https://images.pexels.com/photos/4744755/pexels-photo-4744755.jpeg",
        alt: "Urban Pulse Logo",
        description: "Smart city technologies and urban planning consultancy.",
        isPrime: false,
    },
    {
        id: 7,
        name: "Terra Firma Ltd",
        logoImage: "https://images.pexels.com/photos/15863044/pexels-photo-15863044.jpeg",
        alt: "Terra Firma Ltd Logo",
        description: "Land development and geological engineering.",
        isPrime: true,
    },
    {
        id: 8,
        name: "Crystal Blue Resorts",
        logoImage: "https://images.pexels.com/photos/33440446/pexels-photo-33440446.jpeg",
        alt: "Crystal Blue Resorts Logo",
        description: "High-end resort construction and landscaping.",
        isPrime: false,
    },
    {
        id: 9,
        name: "Zenith Architecture",
        logoImage: "https://images.pexels.com/photos/20716656/pexels-photo-20716656.jpeg",
        alt: "Zenith Architecture Logo",
        description: "Modern minimalist residential designs with a focus on natural light.",
        isPrime: false
    },
    {
        id: 10,
        name: "Urban Core Partners",
        logoImage: "https://images.pexels.com/photos/544295/pexels-photo-544295.jpeg",
        alt: "Urban Core Partners Logo",
        description: "Specializing in mixed-use urban redevelopments and smart infrastructure.",
        isPrime: true,
    },
    {
        id: 11,
        name: "Titan Structures",
        logoImage: "https://images.pexels.com/photos/267399/pexels-photo-267399.jpeg",
        alt: "Titan Structures Logo",
        description: "Engineering durable and iconic industrial complexes globally.",
        isPrime: false,
    },
    {
        id: 12,
        name: "Azure Coastline",
        logoImage: "https://images.pexels.com/photos/33440526/pexels-photo-33440526.jpeg",
        alt: "Azure Coastline Logo",
        description: "Luxury waterfront developments and coastal engineering.",
        isPrime: true,
    },
    {
        id: 13,
        name: "Meridian Heights",
        logoImage: "https://images.pexels.com/photos/988952/pexels-photo-988952.jpeg",
        alt: "Meridian Heights Logo",
        description: "High-rise residential planning with vertical gardens and smart tech.",
        isPrime: true,
    },
    {
        id: 14,
        name: "Nova Build",
        logoImage: "https://images.pexels.com/photos/9973170/pexels-photo-9973170.jpeg",
        alt: "Nova Build Logo",
        description: "Experimental architecture using sustainable and modular materials.",
        isPrime: true,
    },
    {
        id: 15,
        name: "Oasis Dev",
        logoImage: "https://images.pexels.com/photos/4273288/pexels-photo-4273288.jpeg",
        alt: "Oasis Dev Logo",
        description: "Creating green havens and sustainable communities in urban deserts.",
        isPrime: true,
    },
    {
        id: 16,
        name: "Structure Pro",
        logoImage: "https://images.pexels.com/photos/258083/pexels-photo-258083.jpeg",
        alt: "Structure Pro Logo",
        description: "Precision-driven structural engineering for commercial skyscrapers.",
        isPrime: true,
    },
    {
        id: 17,
        name: "Legacy Estates",
        logoImage: "https://images.pexels.com/photos/8998295/pexels-photo-8998295.jpeg",
        alt: "Legacy Estates Logo",
        description: "Preserving architectural heritage through modern restoration and design.",
        isPrime: true,
    },
    {
        id: 18,
        name: "Future Spaces",
        logoImage: "https://images.pexels.com/photos/11035539/pexels-photo-11035539.jpeg",
        alt: "Future Spaces Logo",
        description: "Next-gen workspace design focused on connectivity and collaboration.",
        isPrime: true,
    },
    {
        id: 19,
        name: "Core Steel Group",
        logoImage: "https://images.pexels.com/photos/11035395/pexels-photo-11035395.jpeg",
        alt: "Core Steel Group Logo",
        description: "Heavy-duty steel fabrication and monumental industrial architecture.",
        isPrime: true,
    },
    {
        id: 20,
        name: "Vista Realty",
        logoImage: "https://images.pexels.com/photos/35552681/pexels-photo-35552681.jpeg",
        alt: "Vista Realty Logo",
        description: "Connecting people with premium living spaces and lifestyle properties.",
        isPrime: false,
    },
    {
        id: 21,
        name: "Terra Works",
        logoImage: "https://images.pexels.com/photos/739104/pexels-photo-739104.jpeg",
        alt: "Terra Works Logo",
        description: "Master planning and large-scale site development for global communities.",
        isPrime: false,
    },
    {
        id: 22,
        name: "Orion Designs",
        logoImage: "https://images.pexels.com/photos/2180780/pexels-photo-2180780.jpeg",
        alt: "Orion Designs Logo",
        description: "Aesthetic and functional architectural solutions for modern urban landscapes.",
        isPrime: false,
    },
    {
        id: 23,
        name: "Swift Builders",
        logoImage: "https://images.pexels.com/photos/18111228/pexels-photo-18111228.jpeg",
        alt: "Swift Builders Logo",
        description: "High-efficiency construction management for commercial and industrial projects.",
        isPrime: false,
    },
    {
        id: 24,
        name: "Epic Ventures",
        logoImage: "https://images.pexels.com/photos/24284274/pexels-photo-24284274.jpeg",
        alt: "Epic Ventures Logo",
        description: "Strategic investment and development of high-impact infrastructure.",
        isPrime: false,
    }
]

